<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Platforms>x64</Platforms>
    <AssemblyVersion>03.09.2026.0</AssemblyVersion>
    <FileVersion>03.09.2026.0</FileVersion>
    <Authors>Nozomu-san</Authors>
    <AssemblyTitle>Working Mk II Ammunations for NPC</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Source\Domain.fs" />
    <Compile Include="Source\Stochastic.fs" />
    <Compile Include="Source\Configuration.fs" />
    <Compile Include="Source\Rules.fs" />
    <Compile Include="Source\Game.fs" />
    <Compile Include="Source\State.fs" />
    <Compile Include="Source\Effects.fs" />
    <Compile Include="Source\Runtime.fs" />
    <Compile Include="Source\Script.fs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CommunityScriptHookVDotNetCore">
      <HintPath>..\..\CommunityScriptHookVDotNetCore\CommunityScriptHookVDotNetCore\bin\x64\Release\net10.0\CommunityScriptHookVDotNetCore.dll</HintPath>
    </Reference>
    <Reference Include="LocalNativeMemories">
      <HintPath>..\..\CommunityScriptHookVDotNetCore\LocalNativeMemories\bin\x64\Release\net10.0\LocalNativeMemories.dll</HintPath>
    </Reference>
    <Reference Include="LowLevelEvents">
      <HintPath>..\..\CommunityScriptHookVDotNetCore\LowLevelEvents\bin\x64\Release\net10.0\LowLevelEvents.dll</HintPath>
    </Reference>
    <Reference Include="StandardGameOperations">
      <HintPath>..\..\CommunityScriptHookVDotNetCore\StandardGameOperations\bin\x64\Release\net10.0\StandardGameOperations.dll</HintPath>
    </Reference>
    <Reference Include="StandardJsonConfiguration">
      <HintPath>..\..\DatabaseCore\StandardJsonConfiguration\bin\x64\Release\net10.0\StandardJsonConfiguration.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>